Repository kakahimita/PetResgate, pull requests merged in 2025-05, with the labels that each got.

#1 feat: adicionando a classe usuario
  src/models/Usuario.js
Labels: enhancement

#2 feat: Adicionando a classe pet
  src/models/pet.js
Labels: documentation, enhancement

#3 feat: adicionado a classe para autenticacao do usuario
  src/services/AuthService.js
Labels: enhancement

#4 feat: adicionado a interface
  src/ui/ConsoleUI.js
Labels: enhancement

#5 fix: correcao de importacao para ES6 e nome da classe Pet
  src/models/Pet.js
  src/models/Usuario.js
  src/models/pet.js
  src/services/AuthService.js
  src/ui/ConsoleUI.js
Labels: bug

#6 feat: adicionado a classe de PetService, InitialData e dependencias d…
  node_modules/.package-lock.json
  node_modules/readline-sync/LICENSE
  node_modules/readline-sync/README-Deprecated.md
  node_modules/readline-sync/README.md
  node_modules/readline-sync/lib/encrypt.js
  node_modules/readline-sync/lib/read.cs.js
  node_modules/readline-sync/lib/read.ps1
  node_modules/readline-sync/lib/read.sh
  node_modules/readline-sync/lib/readline-sync.js
  node_modules/readline-sync/package.json
  package-lock.json
  package.json
  src/app.js
  src/seed/initialData.js
  src/services/PetService.js
Labels: enhancement

#7 feat: adicionado a classe ConsoleRender com novos metodos para interf…
  src/app.js
  src/ui/ConsoleRenderer.js
  src/ui/ConsoleUI.js
Labels: enhancement

#9 Create DatabaseService.js
  src/service/DatabaseService.js
Labels: enhancement

#8 test: adicionado testes para a classe usuario, pet, authService e pet…
  .gitignore
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/models/Pet.js
  src/models/test/Pet.test.js
  src/models/test/Usuario.test.js
  src/services/test/AuthService.test.js
  src/services/test/PetService.test.js
Labels: enhancement
